using System;
using System.Windows.Controls;

namespace BellIntegratorTestTask.Views
{
    /// <summary>
    /// Логика взаимодействия для EntityListView.xaml
    /// </summary>
    public partial class EntityListView : UserControl
    {
        public EntityListView()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Action")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

    }
}
