// <auto-generated />
using BellIntegratorTestTask.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BellIntegratorTestTask.DAL.Migrations
{
    [DbContext(typeof(EntitiesDBContext))]
    partial class EntitiesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("BellIntegratorTestTask.Core.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Post")
                        .HasColumnType("TEXT");

                    b.Property<double>("Salary")
                        .HasColumnType("REAL");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Seniority")
                        .HasColumnType("REAL");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = (byte)30,
                            Name = "Semen",
                            Phone = "223322",
                            Post = "Director",
                            Salary = 100000.0,
                            SecondName = "Semenich",
                            Seniority = 10.0,
                            SurName = "Simonov"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = (byte)30,
                            Name = "Neo",
                            Phone = "223322",
                            Post = "Director",
                            Salary = 100000.0,
                            SecondName = "Andersen",
                            Seniority = 10.0,
                            SurName = "Andersen"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = (byte)30,
                            Name = "Ivan",
                            Phone = "223322",
                            Post = "Director",
                            Salary = 100000.0,
                            SecondName = "Ivanovic",
                            Seniority = 10.0,
                            SurName = "Ivanov"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = (byte)30,
                            Name = "Semen",
                            Phone = "223322",
                            Post = "Director",
                            Salary = 100000.0,
                            SecondName = "Semenich",
                            Seniority = 10.0,
                            SurName = "Simonov"
                        });
                });

            modelBuilder.Entity("BellIntegratorTestTask.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Articul")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("Unity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Articul = "11111",
                            Description = "Description about One",
                            Manufacturer = "Pepsico",
                            Name = "One",
                            Price = 300.0,
                            Quantity = 3.0,
                            Unity = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Articul = "11112",
                            Description = "Description about Two",
                            Manufacturer = "Valkure",
                            Name = "Two",
                            Price = 100.0,
                            Quantity = 1.0,
                            Unity = "kg"
                        },
                        new
                        {
                            Id = 3,
                            Articul = "11113",
                            Description = "Description about Three",
                            Manufacturer = "GG",
                            Name = "Three",
                            Price = 200.0,
                            Quantity = 3.0,
                            Unity = "kg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
